[hooks]
pre = ["pre-script.rhai"]
post = ["post-script.rhai"]

[placeholders.registry]
type = "string"
prompt = "[Github action template] To what registry will this policy be published?"
default = "ghcr.io"

[placeholders.registry_module_path_prefix]
type = "string"
prompt = "[Github action template] What registry path prefix will this policy have when publishing?"
default = "kubewarden/policies"

[template]
cargo_generate_version = ">=0.18.0"
include = [
  "Cargo.toml",
  "artifacthub-pkg.yml",
  "artifacthub-repo.yml",
  "metadata.yml",
  "README.md",
  ".github/workflows/release.yml",
]
ignore = ["Makefile", ".github/workflows/cargo-generate-test.yml"]
